# Ethernet-specific configurations
CONFIG_NET_ARP=y
CONFIG_NET_L2_ETHERNET=y

# Ethernet driver stack
# CONFIG_ETH_W5500_RX_THREAD_STACK_SIZE=2048
CONFIG_ETH_W6100_RX_THREAD_STACK_SIZE=2048

CONFIG_ETHERNET_LOG_LEVEL_DBG=y


CONFIG_HEAP_MEM_POOL_SIZE= 32768
CONFIG_UDC_RPI_PICO_STACK_SIZE=1524

CONFIG_UDC_RPI_PICO_THREAD_PRIORITY=1

#usb cdc begin
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_THREAD_STACK_SIZE=2548
# CONFIG_USBD_THREAD_INIT_PRIO=60
CONFIG_STDOUT_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USBD_CDC_ACM_CLASS=y

CONFIG_LOG=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y
CONFIG_USB_DEVICE_PID=0x0004
CONFIG_USB_DEVICE_PRODUCT="Zephyr USB console sample"
#usb cdc end
